### PR TITLE
Sdk 47

### PR DESCRIPTION
**Pull request by pr0n00gler**

### CODE REVIEW

**Comment by pr0n00gler** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/7021790774

**Comment by sotnikov-s** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/7277922171

**Comment by pr0n00gler** [comment]
https://github.com/neutron-org/neutron-tests/actions/runs/7300544995

**Review by swelf19 — COMMENTED** [review]
Seems like you forgot to bump all voting contracts + dustribution contract

**Review by swelf19 — APPROVED** [review]

**Review by sotnikov-s — APPROVED** [review]

**Pull request merged**
